### ISSUE TITLE
Not loading some routes

### ISSUE THREAD

**Issue by spl** [databrary/databrary#11]
I've finally gotten Databrary to run, but it still doesn't load some routes. As shown in the screen shot, it's not loading some Angular templates (`/site/toolbar.html`, `/site/errors.html`, `/site/messages.html`, `/site/tooltip.html`, `/site/home.html`) as well as `/api/volume/9`.

![databrary-not-loading-some-files](https://cloud.githubusercontent.com/assets/54900/21852828/44f103c0-d81d-11e6-8f4d-5cbde3f11f02.png)

If I change the Angular `templateUrl` in various files from `site/` to `web/site`, then the templates are fetched. See the diff below.

But if I create a symbolic link to the `web/site` directory (without changing the `templateUrl`s), it doesn't work:

```sh
~/databrary $ ln -s $PWD/web/site site
```

I'm not sure why `/api/volume/9` is being requested (in `web/service/router.js`).

Any thoughts on what's happening here?

```diff
diff --git a/web/service/router.js b/web/service/router.js
index c9905ee..19a7b4a 100644
--- a/web/service/router.js
+++ b/web/service/router.js
@@ -112,7 +112,7 @@ app.provider('routerService', [

     routes.index = makeRoute(controllers.viewRoot, [], {
       controller: 'site/home',
-      templateUrl: 'site/home.html',
+      templateUrl: 'web/site/home.html',
       resolve: {
         volume: [
           'modelService', 'constantService',
diff --git a/web/site/errors.coffee b/web/site/errors.coffee
index 9015a88..bd2def1 100644
--- a/web/site/errors.coffee
+++ b/web/site/errors.coffee
@@ -5,7 +5,7 @@ app.directive('errors', [
   (display, constants, page) ->
     restrict: 'E'
     scope: {}
-    templateUrl: 'site/errors.html'
+    templateUrl: 'web/site/errors.html'
     link: ($scope) ->
       $scope.page = page
       $scope.$on 'displayService-error', (event, error) ->
diff --git a/web/site/messages.js b/web/site/messages.js
index c54358b..a44e1f6 100644
--- a/web/site/messages.js
+++ b/web/site/messages.js
@@ -13,7 +13,7 @@ app.directive('messages', [

     return {
       restrict: 'E',
-      templateUrl: 'site/messages.html',
+      templateUrl: 'web/site/messages.html',
       controller: controller,
       controllerAs: 'messages',
     };
diff --git a/web/site/notifications.coffee b/web/site/notifications.coffee
index 18ced3c..1687b8c 100644
--- a/web/site/notifications.coffee
+++ b/web/site/notifications.coffee
@@ -4,7 +4,7 @@ app.directive 'notifications', [
   '$sce', '$route', '$rootScope', 'constantService', 'routerService', 'messageService', 'modelService'
   ($sce, $route, $rootScope, constants, router, messages, models) ->
     restrict: 'E'
-    templateUrl: 'site/notifications.html'
+    templateUrl: 'web/site/notifications.html'
     scope:
       close: '&'
     link: ($scope) ->
diff --git a/web/site/toolbar.js b/web/site/toolbar.js
index 9493604..85ab55e 100644
--- a/web/site/toolbar.js
+++ b/web/site/toolbar.js
@@ -5,7 +5,7 @@ app.directive('toolbar', [
   function (page) {
     return {
       restrict: 'E',
-      templateUrl: 'site/toolbar.html',
+      templateUrl: 'web/site/toolbar.html',
       scope: {},
       link: function ($scope) {
         $scope.page = page;
diff --git a/web/site/tooltip.coffee b/web/site/tooltip.coffee
index 706a6d6..1001bf8 100644
--- a/web/site/tooltip.coffee
+++ b/web/site/tooltip.coffee
@@ -5,7 +5,7 @@ app.directive 'tooltip', [
   (window, $timeout) ->
     restrict: 'E'
     scope: false
-    templateUrl: 'site/tooltip.html'
+    templateUrl: 'web/site/tooltip.html'
     link: ($scope) ->
       tooltip = $scope.tooltip
       $scope.classes = []
```

**Comment by spl** [comment]
@dylex Sorry to bother you again, but I'd appreciate any pointers.

**Comment by dylex** [comment]
So, it is true those templateUrls should probably be `web/site/` (I think they were never updated after some reorg), but the reason they work normally is through `web/templates.js`, which should start:
```
app.run(['$templateCache',function(t){
t.put('directive/scrollFloat.html',
```
and have all the templates in it. That is, all the html templates are generated into a single js file that injects them directly into the angular template cache, so it never needs to make a HTTP request.  It sounds as if this file isn't being generated or loaded correctly.

volume 9 is a silly hard-coded fixture for the splash screen -- at some point they wanted to show off one of their datasets and didn't want it to rotate through so I think they just hard-coded a reference to a volume on the production database. It's fine if it fails to load.

**Comment by spl** [comment]
Indeed, it was the `web/templates.js` file. I deleted it (and `web/templates.js.gz`) and rebuilt. Now, I don't see the requests for the files, and it works. I'm not sure how I screwed up the `web/templates.js` file. But thanks!
