### ISSUE TITLE
Active branches to be carved into merge ready soon

### ISSUE THREAD

**Issue by kanishka-azimi** [databrary/databrary#394]
https://github.com/databrary/databrary/compare/kanishka-ingest-0627?expand=1

----
The list above will change frequently as branches get created and deleted. Create a PR only if one desires adding comments. Otherwise, just use the comparison diff links above for viewing.

**Comment by chreekat** [comment]
ping?

**Comment by kanishka-azimi** [comment]
I still use this. There haven't been branches that need intermediate reviews for a few weeks because feature development and bug fixes have slowed down for a bit.

**Comment by kanishka-azimi** [comment]
Reopen when feature dev resumes

**Comment by kanishka-azimi** [comment]
I am going to switch back to creating pull requests for now, and move to a fork in the long run. This issue will be confusing to new comers. I will add a label to in progress PRs.
