### ISSUE TITLE
Unit test example for range set list and other utilities

### ISSUE THREAD

**Issue by kanishka-azimi** [databrary/databrary#40]
I split off the data.rangeset.list module into its own library to be able to write some quick unit tests against it. Feel free to take over this repository or simply duplicate its test into a subfolder of databrary.

https://github.com/kanishka-azimi/range-set-parse

I created a similar test suite for utilities inside of databrary module here:

https://github.com/kanishka-azimi/databrary-util

(Feel free to close this issue)

**Comment by hSloan** [comment]
Thanks! I'll give this some attention as soon as possible.
