### ISSUE TITLE
initdb.sh indiscriminately kills whatever pid is in postgres' pid file.

### ISSUE THREAD

**Issue by chreekat** [databrary/databrary#637]
I'm sure that's never had an ill effect! (Consider system restarts)

**Comment by kanishka-azimi** [comment]
I don't see a problem, given the order in which the scripts are called? I have wanted to replace all the sleep calls with loops.

**Comment by chreekat** [comment]
If the pid file gets left over from a system restart, whatever hapless process that may be using the same pid (since the counter resets with a reboot) will get killed.

**Comment by kanishka-azimi** [comment]
I'd still expect the old pidfile to be deleted, and new one created before reaching the kill line. I might be missing something there?

**Comment by chreekat** [comment]
I see... because postgres is started unilaterally earlier in the same script. Yeah, that's probably safe enough.
